Fixed Global/Sub Twitch Emotes
blay09/EiraMoticons pull request #50
Opened 2017-09-30 20:49 UTC by OscarXcore

This simply updates where the mod gets the emote information from twitchemotes.com and rather fixes the link to reflect the change in the twitchemotes.com v3 API docs as stuff.

2017-10-01 05:24 UTC, blay09 commented
Is this tested with a clean cache? It shouldn't be working just by changing the URL as the actual format of the API response has changed too, e.g.
```json
{
	"VaultBoy": {
		"id": 206490,
		"code": "VaultBoy",
		"emoticon_set": 0,
		"description": null
	},
	"QuadDamage": {
		"id": 206494,
		"code": "QuadDamage",
		"emoticon_set": 0,
		"description": null
	}
}
```
while the code is still looking for a `template` string and `emotes` object, `image_id` instead of `id`, etc.

2017-10-01 21:46 UTC, OscarXcore commented
Ok. Fixed the sub emote registration system when it comes to getting stuff from the API, same with global Twitch emotes as well. The Twitch Turbo Emote Pack won't be created when enabled now because of the fact that Twitch doesn't just have the emotes for Turbo laying around anymore. They are now a client side thing in the web browser by the looks of it.

2017-10-02 05:58 UTC, BlayTheNinth requested changes

2017-10-02 05:58 UTC, blay09 commented on src/api/java/net/blay09/mods/eiramoticons/api/IEmoticon.java
> +    String getCode();
Why change the API? This will break imaginary mods depending on it.

2017-10-02 05:58 UTC, blay09 commented on src/main/java/net/blay09/mods/eiramoticons/addon/pack/TwitchSubscriberPack.java
> +					String channelName = getJsonString(channel, "channel_name");
This should be `display_name`, which is the properly cased version of the channel name (e.g. zeekdageek vs ZeekDaGeek)

2017-10-02 06:00 UTC, blay09 commented
twitchemotes.com doesn't have Turbo emotes anywhere, but they are accessible via Twitch's own API under emoteset 19194

https://api.twitch.tv/kraken/chat/emoticon_images?client_id=gdhi94otnk7c7746syjv7gkr6bizq4w&emotesets=19194

However, that's probably out of scope for this PR.

2017-10-02 18:00 UTC, OscarXcore commented
The recent commit fixes up the Twitch Turbo functionality (renamed everywhere to Twitch Prime) along with the changes you requested that I fix.

2017-10-02 18:06 UTC, OscarXcore commented
Also, this is starting to surprise me on how little issues I have been having with making these changes. I code projects in Javascript... This is the first time I have done anything with a minecraft mod in Java. I think I did pretty good for my first time.

2017-10-11 07:04 UTC, BlayTheNinth approved these changes

2017-10-11 08:46 UTC, merged

2017-10-11 08:47 UTC, blay09 commented
Thanks, will release later

2017-10-11 14:19 UTC, OscarXcore commented
No problem! Thank you as well for approving it!